### ISSUE TITLE
[5.10.40] Crash before the main screen

### ISSUE THREAD

**Issue by Iowowo** [Blood-Asp/GT5-Unofficial#1020]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (Code Chicken Lib.jar)
  IC2core (Industrial Craft 2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 4/11/17 8:36 PM
Description: Initializing game

java.lang.AbstractMethodError
	at ic2.core.crop.CropModel.getTextures(CropModel.java:54)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:163)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:752)
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1185)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145)
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ic2.core.crop.CropModel.getTextures(CropModel.java:54)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:163)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:752)
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1185)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145)
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 191016856 bytes (182 MB) / 1037565952 bytes (989 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D7 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (Code Chicken Lib.jar) 
	UCHIJA	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (Code Chicken Lib.jar) 
	UCHIJA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (Code Chicken Core.jar) 
	UCHIJA	IC2{2.6.188-ex110} [IndustrialCraft 2] (Industrial Craft 2.jar) 
	UCHIJA	gregtech{MC1.10.2} [GregTech] (Gregtech.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (Code Chicken Lib.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
IC2core (Industrial Craft 2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13456 Compatibility Profile Context 21.19.164.257' Renderer: 'AMD Radeon (TM) HD 8500M/8700M'
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Launched Version: Forge 1.10.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) HD 8500M/8700M GL version 4.5.13456 Compatibility Profile Context 21.19.164.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13456 Compatibility Profile Context 21.19.164.257
	OpenGlRenderer: AMD Radeon (TM) HD 8500M/8700M
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

*************
Without Gregtech all works nice.

**Comment by Iowowo** [comment]
I think #1016 is the same problem. However, there are so many mods....

**Comment by Exidex** [comment]
Update Ic2. This is typical crash for old versions of ic2

**Comment by Chocohead** [comment]
Updating IC2 won't change anything, you need to update GT. The latest version is [here](https://wetransfer.com/downloads/81daad74a0f1237a2b1c42a601179d6620170406230833/a5230f), although apparently nowhere else.

#1016 isn't the same problem at all, although I think it is fixed in the new version too.

**Comment by Iowowo** [comment]
Wow, now it works! Thanks a lot! By the way, why this version is not on curse?
