### ISSUE TITLE
[5.09.31pre2]  Crash when having nether wart planted (IC2 Crop)

### ISSUE THREAD

**Issue by Creeperologist** [Blood-Asp/GT5-Unofficial#1160]
Behavior may possibly exist in other crops, however has only been observed in netherwart

nether wart is very commonly used to get a head start of ic2 crops so it can become a big issue when doing crops is so heavily encouraged in gregtech

plus you can get nether wart from breeding through other means so it's a big problem that a central and quite early game feature is causing server crashes

```
java.lang.NullPointerException: Ticking block entity
	at ic2.core.crop.TileEntityCrop.tick(TileEntityCrop.java:191)
	at ic2.core.crop.TileEntityCrop.func_145845_h(TileEntityCrop.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

Update: got more information from the user who's crops it was, there plants had been breeded to what seems like impossible stats, having 35+ growth and gain, (though me not being familiar with ic2 crops, I just remember the high end being much lower than this)

**Comment by draknyte1** [comment]
How about posting your IC2 version?

**Comment by Pyromancer56** [comment]
IC2 2.2.826

**Comment by Creeperologist** [comment]
what pyro said, as well however I got a little more information that the crash doesn't 'just happen' with nether wart, the person causing the crash was in the process of using nether wart to breed them for stats and had reached especially high stat numbers that I don't remember even being possible

growth and gain being near 35+ which doesn't seem normal

**Comment by mura3277** [comment]
@Creeperologist Is the crash itself caused by GT? Does GT need to be installed for this to happen?

**Comment by Blood-Asp** [comment]
Can not replicate this issue with latest GT version.
