### ISSUE TITLE
Crash Microwave Energy Transmitter

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#1206]
nitrogen plasma -> pump->Microwave Energy Transmitter
open GUI, setting world.
nitrogen plasma <-pump<-Microwave Energy Transmitter
open GUI crash (client and server)
[crash-2017-09-09_11.25.49-server.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/1289540/crash-2017-09-09_11.25.49-server.txt)

**Comment by natzgzul89** [comment]
> `---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/9/17 11:25 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_MicrowaveEnergyTransmitter.hasDimensionalTeleportCapability(GT_MetaTileEntity_MicrowaveEnergyTransmitter.java:141)
	at gregtech.common.gui.GT_Container_MicrowaveEnergyTransmitter.func_75142_b(GT_Container_MicrowaveEnergyTransmitter.java:122)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:212)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_MicrowaveEnergyTransmitter.hasDimensionalTeleportCapability(GT_MetaTileEntity_MicrowaveEnergyTransmitter.java:141)
	at gregtech.common.gui.GT_Container_MicrowaveEnergyTransmitter.func_75142_b(GT_Container_MicrowaveEnergyTransmitter.java:122)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:212)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 343
	Entity Name: Natzgull
	Entity's Exact location: -201.77, 86.46, 214.94
	Entity's Block location: World: (-202,86,214), Chunk: (at 6,5,6 in -13,13; contains blocks -208,0,208 to -193,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Natzgull'/343, l='New World', x=-201.77, y=86.46, z=214.94]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: -4726715589824122420
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-184,64,256), Chunk: (at 8,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 751465 game time, 1691040 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57709 (now: false), thunder time: 118638 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 908710520 bytes (866 MB) / 2203582464 bytes (2101 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3072m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	ClientFixer{1.0} [ClientFixer] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	AE2-GT5-P2P{1.0} [AE2-GT5-P2P] (AE2-GT5-p2p-1.7.10-1.0-universal.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18-core.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18-builders.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18-silicon.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18-transport.jar) 
	UCHIJAAAA	ExtrabiomesXL{3.16.4} [ExtrabiomesXL] (extrabiomesxl-1.7.10-3.16.4.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	Forestry{4.2.15.63} [Forestry for Minecraft] (forestry_1.7.10-4.2.15.63.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.11.jar) 
	UCHIJAAAA	CustomOreGen{1.2.24} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24.jar) 
	UCHIJAAAA	DragonsRadioMod{1.7.1} [Dragon's Radio Mod] (Dragon's Radio Mod-MC1.7.10-1.7.1_patched.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynmapModScraper{2.0.0-alpha-1-3} [DynmapModScraper] (DynmapModScraper-2.0.0-forge-10.13.0.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.38_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.38_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.427_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.427_beta.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b199.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	gendustry{1.6.4.135} [GenDustry] (gendustry-1.6.4.135-mc1.7.10.jar) 
	UCHIJAAAA	gvc{0.6.1} [§aGliby's§f Voice Chat Mod] (GlibysVC-1.7.10-0.6.2a.jar) 
	UCHIJAAAA	GraviSuite{2.0.67u} [Graviation Suite] (GraviSuite-1.7.10-2.0.67u1.jar) 
	UCHIJAAAA	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
	UCHIJAAAA	gregtech{MC1710} [GregTech] (gregtech-5.09.31pre4.jar) 
	UCHIJAAAA	GTTweaker{1.0} [GTTweaker] (GTTweaker-1.7.10-1.5.0.jar) 
	UCHIJAAAA	IC2NuclearControl{2.4.2a} [Nuclear Control 2] (IC2NuclearControl-2.4.2a.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAA	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.82-universal.jar) 
	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJAAAA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	Schematica{1.7.6.131} [Schematica] (Schematica-1.7.10-1.7.6.131-universal.jar) 
	UCHIJAAAA	SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
	UCHIJAAAA	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
	UCHIJAAAA	PrivateRegions{@version@} [UltraMine PrivateRegions] (UMPrivateRegions-1.7.10-1.0-client.jar) 
	UCHIJAAAA	UMShops{1.0} [UltraMine Shops] (UMShops-1.7.10-indev-client.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
	UCHIJAAAA	WorldEditCuiFe{1.0.6} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.6-mf-1.7.10-10.13.4.1566.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	List of loaded APIs: 
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
		* BuildCraftAPI|blocks (1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|crops (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|library (2.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.18-core.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|transport (4.1) from Railcraft_1.7.10-9.12.2.0.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from forestry_1.7.10-4.2.15.63.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* CoFHAPI|item (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.427_beta.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.15.63.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.15.63.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.135-mc1.7.10.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.4.2a.jar
		* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.5.1.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|electricity (2.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|signals (2.3.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft_1.7.10-9.12.2.0.jar
		* SchematicaAPI (1.1) from Schematica-1.7.10-1.7.6.131-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.7.10-1.7.6.131-universal.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.12.2.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Natzgull'/343, l='New World', x=-201.77, y=86.46, z=214.94]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 385.41
	OpenGlRenderer: GeForce GTX 690/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`
