### ISSUE TITLE
[5.10.41] Crash on preinitialization after adding Gregtech

### ISSUE THREAD

**Issue by 4erk** [Blood-Asp/GT5-Unofficial#1244]
I added IC2 of latest  version for 1.10.2 (industrialcraft-2-2.6.254-ex110) and launch client - OK
I added CCL of latest version for 1.10.2 (CodeChickenLib-1.10.2-2.5.9.308-universal) and launch client - OK
I added GT of latest version for 1.10.2 (gregtech-5.10.41) and get this crashlog on preinitialization IC2:
` ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.254-ex110.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.308-universal.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 10/11/17 3:18 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech (gregtech)
Caused by: java.lang.NullPointerException
	at gregtech.api.util.GT_Log.init(GT_Log.java:65)
	at gregtech.GT_Mod.onPreLoad(GT_Mod.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.launcher.components.Game$5.run(Game.java:284)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 868465608 bytes (828 MB) / 1365770240 bytes (1302 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xmx3072m -XX:MaxPermSize=128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_E3 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.308-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	mercurius{1.0.6} [Mercurius] (Mercurius-1.9.4-1.0.5.24.jar) 
	UCH	CodeChickenLib{2.5.9.308} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.308-universal.jar) 
	UCH	IC2{2.6.254-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.254-ex110.jar) 
	UCE	gregtech{MC1.10.2} [GregTech] (gregtech-5.10.41.jar) 
	UCH	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCH	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCH	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCH	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCH	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.254-ex110.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.308-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.41' Renderer: 'GeForce GTX 560/PCIe/SSE2'
	CodeChickenLib Invalid Fingerprint Reports: 
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 385.41
	OpenGlRenderer: GeForce GTX 560/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6`

How to be? What to do?

EDIT: try {
forge.version=12.18.3.2422
ic2.version=2.6.254-ex110	
 jei.version=3.14.7.420		
 codechickenlib.version=2.4.3.162
}
catch(Exception e) {
return 'Same log';
}

EDIT2: but server with spongefroge .2477 run perfectly

**Comment by Exidex** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/1196
