### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tacos1** [Blood-Asp/GT5-Unofficial#125]
--- Minecraft Crash Report ----
// Don't do that.

Time: 8/7/15 1:54 AM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at launcher.client.ClientLauncher.launch(ClientLauncher.java:267)
at launcher.client.ClientLauncher.main(ClientLauncher.java:124)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at launcher.client.ClientLauncher.launch(ClientLauncher.java:267)
at launcher.client.ClientLauncher.main(ClientLauncher.java:124)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 390733064 bytes (372 MB) / 1010827264 bytes (964 MB) up to 1010827264 bytes (964 MB)
JVM Flags: 1 total; -Xmx1024M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 56 mods loaded, 56 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge.jar) 
UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge.jar) 
UCHIJA	appliedenergistics2-core{rv2-stable-9} [AppliedEnergistics2 Core] (minecraft.jar) 
UCHIJA	CodeChickenCore{1.0.6.44} [CodeChicken Core] (minecraft.jar) 
UCHIJA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
UCHIJA	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems.jar) 
UCHIJA	ClientFixer{1.0} [ClientFixer] (minecraft.jar) 
UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
UCHIJA	IC2{2.2.757-experimental} [IndustrialCraft 2] (industrialcraft-client.jar) 
UCHIJA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel.jar) 
UCHIJA	appliedenergistics2{rv2-stable-9} [Applied Energistics 2] (appliedenergistics2-client.jar) 
UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] (ArmorStatusHUD-client.jar) 
UCHIJA	Forestry{3.6.0.590-unstable} [Forestry for Minecraft] (Forestry.jar) 
UCHIJA	BinnieCore{2.0-pre8} [Binnie Core] (binnie.jar) 
UCHIJA	Botany{2.0-pre8} [Botany] (binnie.jar) 
UCHIJA	ExtraBees{2.0-pre8} [Extra Bees] (binnie.jar) 
UCHIJA	ExtraTrees{2.0-pre8} [Extra Trees] (binnie.jar) 
UCHIJA	Genetics{2.0-pre8} [Genetics] (binnie.jar) 
UCHIJA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (carpentersblocks_client.jar) 
UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) 
UCHIJA	Railcraft{9.6.1.0} [Railcraft] (Railcraft-client.jar) 
UCHIJA	chisel{2.3.10.686e081} [Chisel 2] (Chisel2.jar) 
UCHIJA	craftguide{1.6.8.1} [CraftGuide] (CraftGuide.zip) 
UCHIJA	endercore{1.7.10-0.0.1.12_alpha} [EnderCore] (EnderCore.jar) 
UCHIJA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO.jar) 
UCHIJA	Waila{1.5.10} [Waila] (Waila.jar) 
UCHIJA	extracells{2.2.73} [Extra Cells 2] (ExtraCells-client.jar) 
UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) 
UCHIJA	gregtech{MC1710} [GregTech] (gregtech.jar) 
UCHIJA	GemBlocksForGreg{1.5.0} [GemBlocksForGreg] (GemBlocksForGreg.jar) 
UCHIJA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-client.jar) 
UCHIJA	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl.jar) 
UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest.jar) 
UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks.jar) 
UCHIJA	movillages{1.2.1} [Mo' Villages] (MoVillages.jar) 
UCHIJA	MrTJPCoreMod{1.0.6.13} [MrTJPCore] (MrTJPCore-1.0.6.13-universal.jar) 
UCHIJA	NEIAddons{1.12.8.29} [NEI Addons] (neiaddons.jar) 
UCHIJA	NEIAddons|AppEng{1.12.8.29} [NEI Addons: Applied Energistics 2] (neiaddons.jar) 
UCHIJA	NEIAddons|Botany{1.12.8.29} [NEI Addons: Botany] (neiaddons.jar) 
UCHIJA	NEIAddons|Forestry{1.12.8.29} [NEI Addons: Forestry] (neiaddons.jar) 
UCHIJA	NEIAddons|CraftingTables{1.12.8.29} [NEI Addons: Crafting Tables] (neiaddons.jar) 
UCHIJA	NEIAddons|ExNihilo{1.12.8.29} [NEI Addons: Ex Nihilo] (neiaddons.jar) 
UCHIJA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins.jar) 
UCHIJA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
UCHIJA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
UCHIJA	ProjRed|Core{4.6.0.79} [ProjectRed] (ProjectRed-Base.jar) 
UCHIJA	ProjRed|Transmission{4.6.0.79} [ProjectRed-Transmission] (ProjectRed-Integration.jar) 
UCHIJA	ProjRed|Exploration{4.6.0.79} [ProjectRed-Exploration] (ProjectRed-World.jar) 
UCHIJA	ProjRed|Compatibility{4.6.0.79} [ProjectRed-Compatibility] (ProjectRed-Compat.jar) 
UCHIJA	ProjRed|Integration{4.6.0.79} [ProjectRed-Integration] (ProjectRed-Integration.jar) 
UCHIJA	ProjRed|Illumination{4.6.0.79} [ProjectRed-Illumination] (ProjectRed-Lighting.jar) 
UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] (StatusEffectHUD-client.jar) 
UCHIJA	Treecapitator{1.7.10} [Treecapitator] (Treecapitator.jar) 
UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.334-universal.jar) 
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 4650'
AE2 Version: stable rv2-stable-9 for Forge 10.13.2.1291
Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
Launched Version: 1.7.10
LWJGL: 2.9.3
OpenGL: ATI Mobility Radeon HD 4650 GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by Blood-Asp** [comment]
I allready answered you in the forum thread. Wrong forge version.

**Comment by tacos1** [comment]
I need to install forge 1481+?

**Comment by JasonMcRay** [comment]
You need to install forge higher than 1481. So its either 1490 or 1492.
