### ISSUE TITLE
Seismic Prospector can't used in the Nether

### ISSUE THREAD

**Issue by Dream-Master** [Blood-Asp/GT5-Unofficial#1351]
Seismic Prospector can't used in the Nether.
Data stick write no nbt data on the stick.

[GT new Horizons Pack]

![image](https://user-images.githubusercontent.com/2970688/34457616-33cfb33e-edb6-11e7-93d6-87a37c489b6a.png)

<gregtech:gt.metaitem.01:32708>.withTag({title: "Raw Prospection Data"})

My guess there is no Oil in the Nether.

**Comment by MauveCloud** [comment]
Looking at the config, both The Nether and The End are blacklisted from generating underground fluids by default, but it ought to still be technicaly possible to use the Seismic Prospector to get the other details it generates, like about ore veins.  If that doesn't work, I agree that this is a bug.

Edit: looking at https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/util/GT_Utility.java#L2119 I'm confused that a lack of oil would prevent the Seismic Prospector from writing data to the stick, so maybe something else is happening here.  The New Horizons fork has the null check as well: https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Utility.java#L2073

**Comment by Dream-Master** [comment]
gt log

```
java.lang.NullPointerException
	at gregtech.common.GT_UndergroundOil.undergroundOil(GT_UndergroundOil.java:61)
	at gregtech.common.GT_UndergroundOil.undergroundOilReadInformation(GT_UndergroundOil.java:25)
	at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_SeismicProspector.onRightclick(GT_MetaTileEntity_SeismicProspector.java:115)
	at gregtech.api.metatileentity.MetaTileEntity.onRightclick(MetaTileEntity.java:231)
	at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1395)
	at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:306)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Encountered Exception while rightclicking TileEntity, the Game should've crashed now, but I prevented that. Please report immediately to GregTech Intergalactical!!!
```

**Comment by Technus** [comment]
@Blood-Asp 
https://github.com/GTNewHorizons/GT5-Unofficial/commit/49122ffb2da78539ca1d29ffa429f6482f5dcaec
https://github.com/GTNewHorizons/GT5-Unofficial/commit/4d4057de3d5d390bfd7e8b1898fbd0686cb174e5

This fixes it, making use of the blacklist (finally?) and making blacklist private method.
