### ISSUE TITLE
[1.10.2 - 5.10.41] Server crashes - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Devlin556** [Blood-Asp/GT5-Unofficial#1517]
Hello! Server crashes 1-2 hours after launch. I see this error in crash reports:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.259-ex110.jar)
  MtqFixPlugin (mtqfix-1.10.2-1.0.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.4-alpha-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  FarseekCoreMod (Farseek_1.9.4_2.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  AppEngLoadingPlugin (appliedenergistics2_rv4_mc1.10.2_stable_1.jar)
  BookshelfLoadingPlugin (Bookshelf_1.10.2_1.4.4.347.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 2/3/19 9:29 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.world.World.func_72827_u()Ljava/lang/String;
	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_73660_a(BaseMetaPipeEntity.java:315)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_73660_a(BaseMetaPipeEntity.java:315)

-- Block entity being ticked --
Details:
	Name: BaseMetaPipeEntity // gregtech.api.metatileentity.BaseMetaPipeEntity
	Block type: ID #991 (gt.blockmachines // gregtech.common.blocks.GT_Block_Machines)
	Block data value: 6 / 0x6 / 0b0110
	Block location: World: (1088,73,236), Chunk: (at 0,4,12 in 68,14; contains blocks 1088,0,224 to 1103,255,239), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Actual block type: ID #991 (gt.blockmachines // gregtech.common.blocks.GT_Block_Machines)
	Actual block data value: 6 / 0x6 / 0b0110
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['M1ster_Sushi'/237931, l='world', x=1142.11, y=66.00, z=170.28]]
	Chunk stats: ServerChunkCache: 915 Drop: 0
	Level seed: -3241506137585344543
	Level generator: ID 06 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (589,64,276), Chunk: (at 13,4,4 in 36,17; contains blocks 576,0,272 to 591,255,287), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 5252610 game time, 5958695 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 66927 (now: false), thunder time: 73387 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-141-generic
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1511923176 bytes (1441 MB) / 3731357696 bytes (3558 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 57 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	IC2{2.6.259-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.259-ex110.jar) 
	UCHIJAAAA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced_Solar_Panels_4.0.4.jar) 
	UCHIJAAAA	animalium{0.1.9} [animalium] (Animalium_1.10.2_0.1.9.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2_rv4_mc1.10.2_stable_1.jar) 
	UCHIJAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJAAAA	bedrockbgone{1.0.4} [Bedrock-B-Gone] (Bedrock_B_Gone_Mod_1.10.2.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands_1.10.2_0.11.1.220f8232fe.jar) 
	UCHIJAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraftv2.2.5MC1.10.2.jar) 
	UCHIJAAAA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf_1.10.2_1.4.4.347.jar) 
	UCHIJAAAA	buildcraftlib{7.89.17-pre3-d86fb23e2451} [BuildCraft Lib] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcraftcore{7.89.17-pre3-d86fb23e2451} [BuildCraft] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcraftbuilders{7.89.17-pre3-d86fb23e2451} [BC Builders] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcraftenergy{7.89.17-pre3-d86fb23e2451} [BC Energy] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcraftfactory{7.89.17-pre3-d86fb23e2451} [BC Factory] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcraftrobotics{7.89.17-pre3-d86fb23e2451} [BC Robotics] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcrafttransport{7.89.17-pre3-d86fb23e2451} [BC Transport] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	buildcraftsilicon{7.89.17-pre3-d86fb23e2451} [BC Silicon] (buildcraft-1.10.2-7.89.17-pre3.jar) 
	UCHIJAAAA	carryon{1.9} [Carry On] (carry-on-mod-1_10_2.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.2.1.46} [Chisel] (Chisel-MC1.10.2-0.2.1.46.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore_1.10.2_2.4.1.102_universal.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (crafttweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2_3.14.7.419.jar) 
	UCHIJAAAA	MineTweaker3{3.0.26} [MineTweaker 3] (crafttweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	cyclicmagic{1.10.27} [Cyclic] (Cyclic_1.10.2_1.10.27.jar) 
	UCHIJAAAA	Waila{1.8.12-B26_1.10.2} [Waila] (Hwyla-1.8.12-B26_1.10.2.jar) 
	UCHIJAAAA	darkutils{1.1.8.finalrc2} [Dark Utilities] (Dark_Utilities_Mod_1.10.2.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage_1.10.2_2.2.1.106_universal.jar) 
	UCHIJAAAA	enderutilities{0.7.4} [Ender Utilities] (enderutilities_1.10.2_0.7.4.jar) 
	UCHIJAAAA	farseek{2.2} [Farseek] (Farseek_1.9.4_2.2.jar) 
	UCHIJAAAA	finite-water-control{1.0} [finite-water-control] (finite_water_control_1.10.2_1.0.jar) 
	UCHIJAAAA	forestry{5.2.17.389} [Forestry] (forestry_1.10.2_5.2.17.389.jar) 
	UCHIJAAAA	gregtech{MC1.10.2} [GregTech] (gregtech-5.10.41.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.1} [JourneyMap] (journeymap-1.10.2-5.5.1.jar) 
	UCHIJAAAA	magma_monsters{0.1.15} [magma_monsters] (MagmaMonsters_0.1.15.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	oreexcavation{1.2.131} [OreExcavation] (OreExcavation-1.2.131.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA8} [Thaumcraft] (Thaumcraft_1.10.2_6.0.BETA8.jar) 
	UCHIJAAAA	railcraft{10.4.1} [Railcraft] (Railcraft_1.10.2-10.4.1.jar) 
	UCHIJAAAA	RTG{4.1.3.0} [Realistic Terrain Generation] (RTG-1.10.2-4.1.3.0-FINAL.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	streams{0.4} [Streams] (Streams-1.9.4-0.4.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	thebetweenlands{2.0.4-alpha} [The Betweenlands] (TheBetweenlands-2.0.4-alpha-universal.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (Tinkers_Tool_Leveling_Mod_1.10.2.jar) 
	UCHIJAAAA	tombmanygraves{1.10.2-2.1.16} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.16.jar) 
	UCHIJAAAA	totemic{1.10.2-0.8.3} [Totemic] (Totemic-1.10.2-0.8.3.jar) 
	UCHIJAAAA	bspkrsCore{at_0.9} [bspkrsCore] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJAAAA	Treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.10.2-at_0.9.jar) 
	UD	mtqfix{1.0.0} [MTQ fix] (minecraft.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.259-ex110.jar)
  
MtqFixPlugin (mtqfix-1.10.2-1.0.0.jar)
  jmn.mods.mtqfix.AsmTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.4-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FarseekCoreMod (Farseek_1.9.4_2.2.jar)
  farseek.core.FarseekClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
AppEngLoadingPlugin (appliedenergistics2_rv4_mc1.10.2_stable_1.jar)
  appeng.coremod.transformer.IntegrationTransformer
BookshelfLoadingPlugin (Bookshelf_1.10.2_1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	AE2 Integration: IC2:ON, RF:ON, RFItem:ON, Waila:ON, THE_ONE_PROBE:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['M1ster_Sushi'/237931, l='world', x=1142.11, y=66.00, z=170.28]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```
Could you help me please?
Minecraft 1.10.2, server forge version is 12.18.3.2316, codeChickenCore version is 1.10.2_2.4.1.102, codeChickenLib version is 1.10.2-2.5.9.267

**Comment by draknyte1** [comment]
1.10 is not supported.
