### ISSUE TITLE
Crash with ic2 #789

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#271]
LOOKING UP ADVANCED CIRCUIT BOARDS IN nei. RUNNING ONLY nei, ic2 AND gt5.09.09

[16:01:11] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at ic2.neiIntegration.core.recipehandler.FluidCannerRecipeHandler.loadCraftingRecipes(FluidCannerRecipeHandler.java:140) ~[FluidCannerRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327) ~[TemplateRecipeHandler.class:?]
	at ic2.neiIntegration.core.recipehandler.FluidCannerRecipeHandler.loadCraftingRecipes(FluidCannerRecipeHandler.java:131) ~[FluidCannerRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465) ~[TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20) ~[GuiCraftingRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.mouseClicked(RecipeItemInputHandler.java:36) ~[RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java) ~[bex.class:?]
	at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:102) ~[GuiRecipe.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
	... 17 more

**Comment by Blood-Asp** [comment]
Hmm also tried only running nei and IC2? There is no GT in the stacktrace.

**Comment by bear989** [comment]
yes, only crashes with GT. also its the circuit board in forming press that
throws the error on the circuit itself.

**Comment by axlegear** [comment]
Confirmed, only occurs if GT5U is present.  Tested with raw MC, IC2 and GT5U.  Works fine if GT5U is removed.

**Comment by Blood-Asp** [comment]
Fixed in ic2-790
