### ISSUE TITLE
Crash with Fossils Archeology Revival

### ISSUE THREAD

**Issue by vrnRaptor** [Blood-Asp/GT5-Unofficial#642]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 23.09.16 0:33
Description: Initializing game

java.lang.RuntimeException: The output ItemStack 1xtile.volcanicAsh@0 is the same as the recipe input RInputOreDict<9xdustAsh>.
    at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
    at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:187)
    at ic2.core.BasicMachineRecipeManager.access$200(BasicMachineRecipeManager.java:36)
    at ic2.core.BasicMachineRecipeManager$1.put(BasicMachineRecipeManager.java:118)
    at ic2.core.BasicMachineRecipeManager$1.put(BasicMachineRecipeManager.java:79)
    at gregtech.api.util.GT_Utility.addSimpleIC2MachineRecipe(GT_Utility.java:864)
    at gregtech.api.util.GT_ModHandler.addCompressionRecipe(GT_ModHandler.java:750)
    at gregtech.loaders.oreprocessing.ProcessingDust.registerOre(ProcessingDust.java:47)
    at gregtech.api.enums.OrePrefixes.processOre(OrePrefixes.java:704)
    at gregtech.common.GT_Proxy.registerRecipes(GT_Proxy.java:203)
    at gregtech.common.GT_Proxy.activateOreDictHandler(GT_Proxy.java:1913)
    at gregtech.GT_Mod.onPostLoad(GT_Mod.java:451)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
    at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:187)
    at ic2.core.BasicMachineRecipeManager.access$200(BasicMachineRecipeManager.java:36)
    at ic2.core.BasicMachineRecipeManager$1.put(BasicMachineRecipeManager.java:118)
    at ic2.core.BasicMachineRecipeManager$1.put(BasicMachineRecipeManager.java:79)
    at gregtech.api.util.GT_Utility.addSimpleIC2MachineRecipe(GT_Utility.java:864)
    at gregtech.api.util.GT_ModHandler.addCompressionRecipe(GT_ModHandler.java:750)
    at gregtech.loaders.oreprocessing.ProcessingDust.registerOre(ProcessingDust.java:47)
    at gregtech.api.enums.OrePrefixes.processOre(OrePrefixes.java:704)
    at gregtech.common.GT_Proxy.registerRecipes(GT_Proxy.java:203)
    at gregtech.common.GT_Proxy.activateOreDictHandler(GT_Proxy.java:1913)
    at gregtech.GT_Mod.onPostLoad(GT_Mod.java:451)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 446734368 bytes (426 MB) / 2056781824 bytes (1961 MB) up to 7635730432 bytes (7282 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   llibrary{1.5.1} [LLibrary](LLibrary v1.5.1.jar) 
    UCHIJ   fossil{7.3.2} [Fossils and Archeology Revival](FossilsArcheologyRevival v7.3.2.jar) 
    UCHIJ   IC2{2.2.825-experimental} [IndustrialCraft 2](IC2 IndustrialCraft-2 v2.2.825-experimental.jar) 
    UCHIE   gregtech{MC1710} [GregTech](IC2 GregTech v5.09.23pre6.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 770/PCIe/SSE2'
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Minecraft 1.7+ Rus by Raptor.zip, Real Sky Resourcepack.zip]
Current Language: Русский (Россия)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Dragon2488** [comment]
@Blood-Asp Because of same issue I was forced to replace IC2 recipe managers in 1.10.

**Comment by Blood-Asp** [comment]
This time tested and working... Test build on OneDrive(gregtech-5.09.26pre.jar)
