### ISSUE TITLE
crash with GT5.09.24 

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#649]
I can load my old world fine and no issues but trying to load it on the server with new world, old world, and limited mods results in this crash

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/27/16 9:00 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
    at gregtech.common.GT_Proxy.onWorldTickEvent(GT_Proxy.java:1222)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_4_GT_Proxy_onWorldTickEvent_WorldTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more
Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 12 more

mods are GT5, IC2, NEI, and underground biomes

**Comment by bear989** [comment]
tested with GT5.09.23 and same crash

**Comment by mura3277** [comment]
Should be fixed by 7b7e0d8

**Comment by Blood-Asp** [comment]
reuploaded .23 and .24 with first fixes.
