### ISSUE TITLE
Fences causing crash when axe used on them. 5.09.24

### ISSUE THREAD

**Issue by konceptum** [Blood-Asp/GT5-Unofficial#650]
Getting the following crash when using an axe on a fence:

java.lang.NullPointerException: Unexpected error
    at gregtech.common.tools.GT_Tool_Axe.isMinableBlock(GT_Tool_Axe.java:83)
    at gregtech.api.items.GT_MetaGenerated_Tool.getDigSpeed(GT_MetaGenerated_Tool.java:438)
    at gregtech.api.items.GT_MetaGenerated_Tool.canHarvestBlock(GT_MetaGenerated_Tool.java:443)
    at net.minecraft.item.ItemStack.func_150998_b(ItemStack.java:319)
    at net.minecraft.entity.player.EntityPlayer.func_82246_f(EntityPlayer.java:1960)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:153)
    at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by mura3277** [comment]
Also present in .23. Fixed by 0ada20e

**Comment by Blood-Asp** [comment]
reuploaded .23 and .24 with fixes.
