### ISSUE TITLE
[1.7.10] Concurrent modification exception while drawing tooltips

### ISSUE THREAD

**Issue by codewarrior0** [Blood-Asp/GT5-Unofficial#720]
```
[07:44:09] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_73]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_73]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_73]
	at java.util.Hashtable.putAll(Unknown Source) ~[?:1.8.0_73]
	at cpw.mods.fml.common.registry.LanguageRegistry.injectLanguage(LanguageRegistry.java:253) ~[LanguageRegistry.class:?]
	at gregtech.api.util.GT_LanguageManager.addStringLocalization(GT_LanguageManager.java:28) ~[GT_LanguageManager.class:?]
	at gregtech.api.util.GT_LanguageManager.addStringLocalization(GT_LanguageManager.java:21) ~[GT_LanguageManager.class:?]
	at gregtech.common.items.GT_IntegratedCircuit_Item.addAdditionalToolTips(GT_IntegratedCircuit_Item.java:82) ~[GT_IntegratedCircuit_Item.class:?]
	at gregtech.api.items.GT_Generic_Item.func_77624_a(GT_Generic_Item.java:98) ~[GT_Generic_Item.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525) ~[add.class:?]
	at forestry.core.gui.widgets.ItemStackWidgetBase.getToolTip(ItemStackWidgetBase.java:41) ~[ItemStackWidgetBase.class:?]
	at forestry.core.gui.GuiUtil.drawToolTips(GuiUtil.java:133) ~[GuiUtil.class:?]
```

`gregtech-5.09.25`
`forestry_1.7.10-4.2.16.64`
`forge-1.7.10-10.13.4.1614`

Happens occasionally when opening a Forestry Worktable that contains an Integrated Circuit, either in its storage or as a stored recipe. May be either Forestry's or Gregtech's fault - can't tell at this point.

The CME indicates that another thread has modified the language registry at the same time as the client thread attempted to modify it. This means I should eventually get the same error but on the side of the other thread. I will update this issue when it happens.

<sub>Or if we're lucky, someone else has the other half of this error and finds this issue.</sub>

**Comment by Blood-Asp** [comment]
You might try 5.09.26pre from onedrive. I did some changes on that class. Not because of that issue, but might take care of it already.

**Comment by codewarrior0** [comment]
Still happens in 5.09.27

**Comment by codewarrior0** [comment]
I got this same crash several more times, each time with the same trace where the Client Thread is calling through `forestry.core.gui.widgets.ItemStackWidgetBase.getToolTip` to hit the CME in `cpw.mods.fml.common.registry.LanguageRegistry.injectLanguage`

After some fiddling, I attached the IntelliJ IDEA remote debugger and set a breakpoint on `injectLanguage` and found that the *other thread* I mentioned may be the NEI Item Filtering thread:

```
	  at cpw.mods.fml.common.registry.LanguageRegistry.injectLanguage(LanguageRegistry.java:247)
	  at gregtech.api.util.GT_LanguageManager.addStringLocalization(GT_LanguageManager.java:33)
	  at gregtech.common.blocks.GT_Item_Machines.func_77624_a(GT_Item_Machines.java:53)
	  at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	  at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119)
	  at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162)
	  at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:529)
	  at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:65)
	  at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:110)
	  at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:85)
	  at codechicken.nei.ItemList$2.execute(ItemList.java:239)
	  at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24)
```

This would be where I go ask the FML guys why `injectLanguage` isn't thread safe, but this version of FML is no longer maintained. The next option would be to bug the NEI team, but again NEI for 1.7.10 is no longer maintained. So the final option is to hack away at NEI myself and try to get the NEI Item Filtering thread to stop calling `injectLanguage`.

**Comment by codewarrior0** [comment]
Anyway, feel free to mark this one as "Not my fault" - it looks like NEI is the culprit this time.

**Comment by mura3277** [comment]
At least the cause was found

**Comment by codewarrior0** [comment]
Actually, I take it back. I just proved that even if `injectLanguage` is made into a synchronized method, the CME still occurs. A closer look at the traceback shows that the collection being concurrently modified is not a value of `LanguageRegistry.modLanguageData` (as I originally thought), but is the collection passed as the `parsedLangFile` param to `injectLanguage`. So while NEI has a hand in what's happening, it looks like the fault is with GregTech: its `addStringLocalization` method is not thread safe.

In `GT_LanguageManager.addStringLocalization`, a static member `TEMPMAP` is modified, passed to `injectLanguage` as its `parsedLangFile` param, and then cleared. This method will be called on the main thread while the worktable is open. If the NEI thread calls this method while the main thread is inside `injectLanguage`, iterating through `TEMPMAP`, it will modify `TEMPMAP` thus causing the main thread to raise the CME.

~- Change `TEMPMAP` to a local variable~

The fix is almost certainly to declare `GT_LanguageManager.addStringLocalization` as a synchronized method, since it may also concurrently modify `LANGMAP`

**Comment by Blood-Asp** [comment]
The best change would likely be: Do not change localization entrys anymore after startup. So only read, no write after GregTech_API.sPostloadFinished == true

**Comment by codewarrior0** [comment]
That might work. It would cause a small problem for translators, though. The tooltips for most GT items that are not MetaTileEntities will not be written to the lang file until the item is moused over (or until NEI fetches its tooltip for searching/filtering purposes). The same applies for written books printed by a Printer (e.g. prospection data and assembly line books) and several lines used when the Portable Scanner is used on some multiblock controllers.

I added synchronized to `addStringLocalization` and haven't seen the crash after using the workbench for a couple of days. I measured the game startup time too, which didn't increase by more than a second or two. I'll just send that in as the fix. 

Later (probably never) we can look at the wider problem, which is GT's lang system writing lang files at runtime at all. The sane approach is to build the lang files at build time using a Java source code parser and a special marker for translatable strings.

**Comment by Bogdan-G** [comment]
change the language(localization changes) must be before the start of the game, what it does during a game? if the player to change the language in the play game - so, why else?
strange, but i was not crash on this occasion, the maximum error in the log, and no more than. Perhaps a bug somewhere else.

**Comment by codewarrior0** [comment]
@Bogdan-G It's not about changing the language. It's about getting the initial English language file, which is created during gameplay. Some translation lines aren't added unless you actually go do a specific thing in-game. But that's outside the scope of this issue.

**Comment by Bogdan-G** [comment]
>which is created during gameplay

whether it is possible to make so that it was during the launch of the game to the main menu?

**Comment by Dragon2488** [comment]
You need to search many usages in code, plus it will kill flexibility of language system.
