### ISSUE TITLE
Kicked from server when breaking Coal ore or Lignite coal

### ISSUE THREAD

**Issue by demethan** [Blood-Asp/GT5-Unofficial#759]
I'm having issues with mining Coal and Lignite Coal.

its when picking up the ore block after mining it.   I get kicked from the server.

forge 1.10.2-12.18.2.2125
GT-addon (tried 5.10..06 then .05)

`18:07:43] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /127.0.0.1:55390
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 10538 on block gregtech:gt.blockores, it is not an allowed value
	at net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.func_177226_a(ExtendedBlockState.java:100) ~[ExtendedBlockState$ExtendedStateImplementation.class:?]
	at gregtech.api.items.GT_Generic_Block.func_176203_a(GT_Generic_Block.java:52) ~[GT_Generic_Block.class:?]
	at toughasnails.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:35) ~[AchievementEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_190_AchievementEventHandler_onItemPickup_ItemPickupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:580) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:410) ~[yk.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570) ~[zs.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
	... 9 more`

**Comment by GordonHollow** [comment]
toughasnails.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:35) 

this mod from BoP developers has the same issue https://github.com/Blood-Asp/GT5-Unofficial/issues/756
in latest BoP - fixed, in toughasnails - shoul be fixed by it's developers

**Comment by demethan** [comment]
Ok.. thx
