### ISSUE TITLE
[1.10.2] Sound effects cause the sound system to crash

### ISSUE THREAD

**Issue by Tupas1** [Blood-Asp/GT5-Unofficial#812]
This includes sounds that are played when GT tools are broken and when crafting with the hammer, could also be some others. After that no other sounds will be played until the game is restarted.
Something like this appears in the console:
```
[22:50:01] [Thread-12/ERROR]: Error in class 'CodecJOrbis'
[22:50:01] [Thread-12/ERROR]: Unable to acquire inputstream in method 'initialize'.
[22:50:01] [Thread-12/WARN]: ERROR MESSAGE:
[22:50:01] [Thread-12/INFO]: minecraft:sounds/random.break.ogg
[22:50:01] [Thread-12/WARN]: STACK TRACE:
[22:50:01] [Thread-12/INFO]: net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68)
[22:50:01] [Thread-12/INFO]: net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
[22:50:01] [Thread-12/INFO]: net.minecraft.client.audio.SoundManager$2$1.getInputStream(SoundManager.java:496)
[22:50:01] [Thread-12/INFO]: paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:281)
[22:50:01] [Thread-12/INFO]: paulscode.sound.libraries.SourceLWJGLOpenAL.play(SourceLWJGLOpenAL.java:616)
[22:50:01] [Thread-12/INFO]: paulscode.sound.Library.play(Library.java:706)
[22:50:01] [Thread-12/INFO]: paulscode.sound.Library.play(Library.java:675)
[22:50:01] [Thread-12/INFO]: paulscode.sound.SoundSystem.CommandPlay(SoundSystem.java:2076)
[22:50:01] [Thread-12/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2599)
[22:50:01] [Thread-12/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
[22:50:01] [Thread-12/ERROR]: Error in class 'SourceLWJGL OpenAL'
[22:50:01] [Thread-12/ERROR]: Audio Format null in method 'play'
Exception in thread "Thread-12" [22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.codecs.CodecJOrbis.cleanup(CodecJOrbis.java:404)
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.Source.cleanup(Source.java:363)
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.libraries.SourceLWJGLOpenAL.cleanup(SourceLWJGLOpenAL.java:208)
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.Library.removeSource(Library.java:1086)
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.SoundSystem.CommandRemoveSource(SoundSystem.java:2185)
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2538)
[22:50:02] [Thread-12/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.CommandThread.run(CommandThread.java:121)
```

**Comment by Dragon2488** [comment]
Fixed.
