### ISSUE TITLE
modular armour

### ISSUE THREAD

**Issue by natzgzul89** [Blood-Asp/GT5-Unofficial#851]
[11:31:33] [WARN] Failed to handle packet for /92.125.0.240:63540
net.minecraft.util.ReportedException: Ticking player
 at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:302)
 at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:318)
 at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:34)
 at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:232)
 at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:231)
 at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
 at gregtech.common.items.armor.ModularArmor_Item.onArmorTick(ModularArmor_Item.java:341)
 at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:319)
 at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:541)
 at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
 at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:291)
 at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:248)
 ... 10 more

**Comment by natzgzul89** [comment]
`
[17:47:59] [WARN] Failed to handle packet for /95.181.104.70:52578
java.lang.NullPointerException
 at gregtech.common.items.armor.ModularArmor_Item.getProperties(ModularArmor_Item.java:128)
 at net.minecraftforge.common.ISpecialArmor$ArmorProperties.ApplyArmor(ISpecialArmor.java:112)
 at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1090)
 at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:785)
 at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1037)
 at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:452)
 at net.minecraft.entity.EntityLivingBase.func_70069_a(EntityLivingBase.java:1014)
 at net.minecraft.entity.player.EntityPlayer.func_70069_a(EntityPlayer.java:1779)
 at net.minecraft.entity.Entity.func_70064_a(Entity.java:923)
 at net.minecraft.entity.EntityLivingBase.func_70064_a(EntityLivingBase.java:182)
 at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:558)
 at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:420)
 at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:34)
 at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:99)
 at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:231)
 at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)
[17:47:59] [INFO] [Disconnect] User 'COKOJI' lost connection: Internal server error
`
5.09.27
