### ISSUE TITLE
[1.10.2] NullPointerException on chunk generation

### ISSUE THREAD

**Issue by Tupas1** [Blood-Asp/GT5-Unofficial#854]
Something related to the generation of ores:
```
java.lang.NullPointerException
 	at gregtech.common.blocks.GT_Block_GeneratedOres.setOreBlock(GT_Block_GeneratedOres.java:106)
	at gregtech.common.GT_Worldgen_GT_Ore_SmallPieces.executeWorldgen(GT_Worldgen_GT_Ore_SmallPieces.java:57)
	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:95)
	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:54)
 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:106)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at gregtech.common.blocks.GT_Block_GeneratedOres.setOreBlock(GT_Block_GeneratedOres.java:106)
	at gregtech.common.GT_Worldgen_GT_Ore_SmallPieces.executeWorldgen(GT_Worldgen_GT_Ore_SmallPieces.java:57)
	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:95)
	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:54)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
 	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at net.minecraft.world.World.func_180496_d(World.java:515)
	at net.minecraft.world.World.func_175685_c(World.java:466)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.world.World.func_175656_a(World.java:408)
	at gregtech.common.GT_Worldgen_Stone.executeWorldgen(GT_Worldgen_Stone.java:78)
 	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:95)
	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:54)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:106)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)
```
These two errors appear first (first one of them gets repeated a bunch of times), after that it just spams `[Server thread/ERROR] [gregtech/]: java.lang.NullPointerException` without any additional details. IIRC this began in version 30.
[Full logs](https://www.dropbox.com/s/4yln0q4s2tts8j2/logs.zip?raw=1)

**Comment by DanielCordell** [comment]
I'm getting a slightly different variant of the log, referencing quark and harvestcraft. Game has tick lag and is basically unplayable. 
`[02:15:43] [Server thread/ERROR]: java.lang.NullPointerException
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.blocks.GT_Block_GeneratedOres.setOreBlock(GT_Block_GeneratedOres.java:106)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.GT_Worldgen_GT_Ore_SmallPieces.executeWorldgen(GT_Worldgen_GT_Ore_SmallPieces.java:57)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:95)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:54)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.blocks.GT_Block_GeneratedOres.setOreBlock(GT_Block_GeneratedOres.java:82)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.GT_Worldgen_GT_Ore_Layer.executeWorldgen(GT_Worldgen_GT_Ore_Layer.java:113)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.GT_Worldgenerator.generateInternal(GT_Worldgenerator.java:77)
[02:15:43] [Server thread/ERROR]: 	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:54)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
[02:15:43] [Server thread/ERROR]: 	at vazkii.quark.world.world.StoneInfoBasedGenerator.generate(StoneInfoBasedGenerator.java:59)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:37)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:81)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:37)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:56)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:37)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:66)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:37)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:76)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_72964_e(World.java:303)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175726_f(World.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_180495_p(World.java:842)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.World.func_175623_d(World.java:223)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.blocks.blocks.BlockBaseGarden.func_176196_c(BlockBaseGarden.java:105)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generateGarden(BushWorldWorldGen.java:72)
[02:15:43] [Server thread/ERROR]: 	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generate(BushWorldWorldGen.java:45)
[02:15:43] [Server thread/ERROR]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:174)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
[02:15:43] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
[02:15:43] [Server thread/ERROR]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by FoxZOolm** [comment]
same.. but server works as fine... and I dont see any problem on chunkgen

**Comment by GordonHollow** [comment]
Same situation and chunk generation VERY SLOW
Version 22 has faster generation in 2-3 times.

**Comment by Dragon2488** [comment]
Then something is wrong with your modpack. From 22 generation performance incresed drastically.

**Comment by GordonHollow** [comment]
GT 22 -> GT 34 with my modpack
Loading game perfomance increase 2 times
Generation world perfomance decrease 3 times
And massively memory draining. With 7.5Gb dedicated to Java it's draining all 16Gb and turned off when generated new chunks. 22 version works fine.

**Comment by codewarrior0** [comment]
Did some investigating. The problem is that the worldgen options are set to generate Jasper Small Ores, but the material options are set to never create the Jasper Small Ore block. The fix is either to change Materials.java to create ores for Jasper, or to change GT_Worldgenloader.java to remove the `ore.small.jasper` line.

I'd rather change the worldgen. Jasper is kind of a crap ore.

**Comment by Rongmario** [comment]
Still happening on GT5.10.34: https://gist.githubusercontent.com/Rongmario/c6753ae64cc0479f21388fc6be74625d/raw/9d7be80e6b67df8f62b164015cc587706deaae64/gistfile1.txt

**Comment by codewarrior0** [comment]
As a quick fix, you can go to your `GregTech/WorldGeneration.cfg` and change this line to `=false`:

`    B:ore.small.jasper_true=true`

**Comment by GordonHollow** [comment]
With this quickfix console spam stoped, but i can't create world anyway, cause generation sloooow
Use another modpack with newer Forge - same result

sometimes console says 
> [15:31:38] [Server thread/WARN]: Tried to over-fill a container
when try to create world

**Comment by Dragon2488** [comment]
which mods do you use? Some mods can trigger vein generation in neighbour chunks, resulting chain reaction and very slow generation. Try removing all generation-changing mods.

**Comment by GordonHollow** [comment]
I try create RTG-world and it don't create
I try create BOP-world and it don't create
Vanilla worldtype don't create world too

Or it's created world but so lagging, such as server lags (don't drop blocks, can't open any GUI)

**Comment by Dragon2488** [comment]
i need full modlist.

**Comment by Dragon2488** [comment]
for me RTG world with BOP biomes generates perfectly.

**Comment by GordonHollow** [comment]
https://minecraft.curseforge.com/projects/mc-the-final-frontier this modpack(modlist in spoiler there)
and optifine (not interferre with generation)

and deleted pamharvestcraft from this modpack cause https://github.com/Blood-Asp/GT5-Unofficial/issues/828

**Comment by GordonHollow** [comment]
I wait about 30min, world created and loaded...but so many skipping ticks that it can't be played
I just open vanilla furnace GUI and have this

`14:39:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent$Entity@658abb2f:
> java.lang.NullPointerException
> 	at toast.specialAI.ai.grief.EntityFakePlayer.func_70089_S(EntityFakePlayer.java:78) ~[EntityFakePlayer.class:?]
> 	at slimeknights.toolleveling.EntityXpHandler.onCapabilityAttach(EntityXpHandler.java:20) ~[EntityXpHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1202_EntityXpHandler_onCapabilityAttach_Entity.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
> 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:565) [ForgeEventFactory.class:?]
> 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:550) [ForgeEventFactory.class:?]
> 	at net.minecraft.entity.Entity.<init>(Entity.java:205) [rw.class:?]
> 	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:155) [sf.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:158) [zs.class:?]
> 	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:142) [lu.class:?]
> 	at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:42) [FakePlayer.class:?]
> 	at toast.specialAI.ai.grief.EntityFakePlayer.<init>(EntityFakePlayer.java:34) [EntityFakePlayer.class:?]
> 	at toast.specialAI.ai.grief.EntityAIGriefBlocks.updateTaskFiddling(EntityAIGriefBlocks.java:339) [EntityAIGriefBlocks.class:?]
> 	at toast.specialAI.ai.grief.EntityAIGriefBlocks.func_75246_d(EntityAIGriefBlocks.java:263) [EntityAIGriefBlocks.class:?]
> 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [tr.class:?]
> 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900) [sg.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183) [sf.class:?]
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685) [sg.class:?]
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47) [yx.class:?]
> 	at net.minecraft.entity.monster.EntitySkeleton.func_70636_d(SourceFile:184) [zd.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384) [sg.class:?]
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52) [yx.class:?]
> 	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
> 	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
> 	at net.minecraft.world.World.func_72939_s(World.java:1750) [aid.class:?]
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

**Comment by Dragon2488** [comment]
It's SpecialAI error.

**Comment by GordonHollow** [comment]
I see, but it don't crash, just console message
Game lagging as hell after 30 min of creating world
Without GT this modpack don't lags for me

I try removed all mods that triggered any console error, but it don't helps still
Just very slow creating, loading and playing, skipping many ticks
Don't have idea what mod do this when interferre with GT, it can be very simple API or core-mod that change something small but important for GT things

**Comment by GordonHollow** [comment]
Exploring new chunks trigger about 20min generate without crashes or console message
