### ISSUE TITLE
Client crash with Forge 1.7.10-10.13.4.1448

### ISSUE THREAD

**Issue by ET-Bent** [Blood-Asp/GT5-Unofficial#86]
First of all the client crash report can be found here: http://pastebin.com/ccAZe48d

The problem seems to be with changes in forges fluid registry. In the crash report you can see forge complaining about fluids that are already registered. The crash in the client happens when you join the server. For a few seconds it tries to log in, then Minecraft crashes. In the server console you get the following error:

```
java.io.IOException: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_45]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_45]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_45]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_45]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_45]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

This error also occurs on a very simple server/client setup only running:
* gregtech_1.7.10-5.08.23.jar 
* industrialcraft-2-2.2.746-experimental.jar

Let me know if you need more information. I will try never forge versions but those might break some other mods in my official pack.

For all testing the following Java was used:
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by JasonMcRay** [comment]
It is not GregTech issue. It is forge issue which has been reported numerous times already if I am not mistaken (https://github.com/MinecraftForge/MinecraftForge/issues/1973).
Dupe #58

**Comment by ET-Bent** [comment]
Thanks seems to be the issue, I hope the'll fix this because some mods depend on never forge versions.

**Comment by ET-Bent** [comment]
Only for information, latest working Forge with GT5: 10.13.3.1424.

Blood-Asp and cpw got into a discussion there, hope this get's fixed soon ;)

**Comment by Blood-Asp** [comment]
Should be fixed in the next forge build (1488+) once it is out. I hope someone can test it for me then.
