### ISSUE TITLE
NPE in GT_MetaTileEntity_SteamTurbine.getFuelValue

### ISSUE THREAD

**Issue by vlad20012** [Blood-Asp/GT5-Unofficial#864]
```
java.lang.NullPointerException
	at gregtech.common.tileentities.generators.GT_MetaTileEntity_SteamTurbine.getFuelValue(GT_MetaTileEntity_SteamTurbine.java:59)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicGenerator.allowPutStack(GT_MetaTileEntity_BasicGenerator.java:259)
	at gregtech.api.metatileentity.MetaTileEntity.func_102007_a(MetaTileEntity.java:679)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_102007_a(BaseMetaTileEntity.java:1631)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:387)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:375)
	at com.enderio.core.common.util.ItemUtil.doInsertItem(ItemUtil.java:325)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:380)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:343)
	at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:257)
	at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:226)
	at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:155)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:214)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_187_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.postWithProfile(EventBus.java:179)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:250)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:620)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)
```

**Comment by DEMOOH** [comment]
Can you reproduce it and give us some details?

**Comment by vlad20012** [comment]
Insert an item instead of steam into SteamTurbine via pipe (EnderIO).

**Comment by Dragon2488** [comment]
You need AT LEAST provide gt version and full log.

**Comment by vlad20012** [comment]
Этого стэктрейса достаточно, чтобы понять все об этой проблеме, в т.ч. о версии и о воспроизводимости. Версия - сборано из unstable ветки. Но по слухам, это работает уже очень давно, возможно на всех версиях. Кто-то на сервере подключил item conduit EnderIO к паровой турбине, на этом сервер крашнулся и крашился при каждом запуске. За 5 мин вшил null-чеки в GT_MetaTileEntity_SteamTurbine.getFuelValue(), так и работает, но это явно костыль.
Требуется дополнительное изучение, откуда null дотуда вообще доехал, поэтому я опубликовал здесь этот стэктрейс, а не прислал PR с null-чеками.

**Comment by JasonMcRay** [comment]
Can confirm this happened just yesterday on my server. Using GT 5.09.28pre (also am able to recreate in 5.09.27) and eIO 2.3.0.429.

Connected ednerIo item conduit to the steam turbine and when the conduit tried to move an item in it, crash occured.

http://paste.ee/p/HQ3Vp

**Comment by Dragon2488** [comment]
Этого стактрейса НЕ доствточно. Гадать по ебаным именам классов версию грегтеча никто не будет.

**Comment by draknyte1** [comment]
While using EnderCore-1.7.10-0.2.0.34_beta/EnderIO-1.7.10-2.3.0.424_beta & GT 5.09.27, I cannot get this crash to occur. Must be on the EIO/Core side.

**Comment by Blood-Asp** [comment]
Seems the important part is not that EnderIO does insert something, but what sort of item the automation did try to insert. Added more null checks that should prevent crashes here.
