### ISSUE TITLE
Blocks re-appear in inventory after placement in the world

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#874]
Blocks affected so far are machine blocks, namely Bronze plated blast furnance and Diesel generator. Bronze bricks are not affected. 

If I place the re-appeared block in the world and break it via normal means (wrench), client disconnects with "Internal server error". After re-login, block is still in my inventory and everything proceeds fine, unless I try to place it again.

log bit:

https://paste.kde.org/pmhbnrgfa

```
<...>
[01:40:07] [Server thread/WARN]: Failed to handle packet for /10.0.0.2:42714
net.minecraft.util.ReportedException: Ticking player
<...>
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 1110 on block gregtech:gt.blockmachines, it is not an allowed value
<...>
   at gregtech.api.items.GT_Generic_Block.func_176203_a(GT_Generic_Block.java:125) ~[GT_Generic_Block.class:?]
    at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:58) ~[AchievementEventHandler.class:?]
```

**Comment by ghost** [comment]
This is happening on GT version 5.10.34; with Minecraft 1.10.2 and Forge 2185

**Comment by Dragon2488** [comment]
`at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:58)`

**Comment by Dragon2488** [comment]
Also it was already fixed. List issues first. Update your BOP version.
