### ISSUE TITLE
[1.10.2] Graphical Glitches/weirdness on 5.10.40

### ISSUE THREAD

**Issue by xF4m3** [Blood-Asp/GT5-Unofficial#901]
So as already stated in Discord by different people, there are Graphical glitches that popup at random as far as i can tell, sometimes every few seconds, and at other times it takes a little while longer. 
Glitches include small ore's looking like stone for a brief moment, changing back and forth (flickering). 
Randomly whole sides of Machines get completly invisible, sometimes multiple sides at once, at other times only one. I noticed this especially on the Centrifuge, but that might be just a Coincedence.

Best Regards
xF4m3

**Comment by MauveCloud** [comment]
Are you using Optifine with Anisotropic Filtering and/or Antialiasing active?  I haven't built any machines yet, but with at least one of those options active, bauxite and ilmenite ore show up as either flat colored blocks or act like x-ray blocks; with both turned off (or Optifine disabled), the ores show up normally.

Edit: I might have spoken too soon about having both options turned off being enough.  I saw one ore block act up while others looked normal when I did that (as opposed to all of them looking wrong).  Having Optifine disabled seems more reliable so far.

Edit 2: not completely reliable, though.  I came across a lignite vein where one of the ores was giving the x-ray effect for _part_ of the substrate, which looked really freaky:
![2017-02-20_21 46 05](https://cloud.githubusercontent.com/assets/8942955/23152459/11d547f8-f7b7-11e6-9a8e-ba14517094e5.png)

**Comment by MauveCloud** [comment]
Further update: I found some black granite (without ores) that acted like this, despite black granite not being a tile entity as far as I can tell:
![2017-02-21_10 39 01](https://cloud.githubusercontent.com/assets/8942955/23179273/2b059c26-f822-11e6-82a4-03f124a911c3.png)

**Comment by xF4m3** [comment]
If Anisotropic Filtering is on in optifine by default, I have it on, otherwise its still off, I can't check at the moment though, I might update you on this later. For Antialiasing, that is definetly turned off. But I Indeed do have Optifine installed. Also nice seeing someone else use Sphax hehe

**Comment by MauveCloud** [comment]
I think AF is off by default, iirc I had to turn it on to see what difference it made.  However, the screenshots I attached are with Optifine disabled, so obviously it's not enough to completely prevent this effect.  It seems somewhat less common with Optifine disabled, though.

**Comment by MauveCloud** [comment]
I've been wondering lately if this could have something to do with the lack of blockstate and model json files in the assets folder for GT 5.10, which is somewhat backed up by these lines in the log:
```
[07:29:03] [Client thread/ERROR] [FML]: Exception loading model for variant gregtech:gt.blockores.114#metadata=1
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model gregtech:gt.blockores.114#metadata=1 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:252) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:240) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1195) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 26 more
[07:29:03] [Client thread/ERROR] [FML]: Exception loading blockstate for the variant gregtech:gt.blockores.114#metadata=1: 
java.lang.Exception: Could not load model definition for variant gregtech:gt.blockores.114
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:285) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:121) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:240) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model gregtech:blockstates/gt.blockores.114.json
	at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:205) ~[byo.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:185) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:281) ~[ModelLoader.class:?]
	... 25 more
Caused by: java.io.FileNotFoundException: gregtech:blockstates/gt.blockores.114.json
	at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:103) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:79) ~[bxi.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:198) ~[byo.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:185) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:281) ~[ModelLoader.class:?]
	... 25 more
[07:29:03] [Client thread/ERROR] [FML]: Exception loading model for variant gregtech:gt.blockores.114#metadata=0
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model gregtech:gt.blockores.114#metadata=0 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:252) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:240) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1195) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 26 more
[07:29:03] [Client thread/ERROR] [FML]: Exception loading model for variant gregtech:gt.blockores.114#metadata=5
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model gregtech:gt.blockores.114#metadata=5 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:252) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:240) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1195) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 26 more
[07:29:03] [Client thread/ERROR] [FML]: Exception loading model for variant gregtech:gt.blockores.114#metadata=4
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model gregtech:gt.blockores.114#metadata=4 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:252) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:240) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1195) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 26 more
[07:29:03] [Client thread/ERROR] [FML]: Suppressed additional 2878 model loading errors for domain gregtech
```

Unfortunately, I don't even know how to figure out what filenames it is expecting in the GregTech assets folder for this.

**Comment by MauveCloud** [comment]
One other thing I've noticed that might be relevant: for me at least, machine textures tend to remain stable close up.  It's only when I'm about 30 blocks or more away that they start flickering.

**Comment by draknyte1** [comment]
Models are missing because they're generated in game. As far as I'm aware.

**Comment by codewarrior0** [comment]
Oh, I think I fixed this at one point, but never sent in the patch. Lemme see if I can find it...

**Comment by codewarrior0** [comment]
Oh, someone one else has touched the render code since then. Don't feel like resolving merge conflicts right now, but here's the idea:

`gregtech.common.render.RenderBlocks` is a singleton used by `GT_Renderer_Blocks` and friends. Because MC now has threaded rendering, this means `GT_Renderer_Blocks` can be called simultaneously on both the client thread and the chunk update thread. This means the singleton has state (e.g. the current bounding box) that is modified by both threads concurrently, causing the apparent rendering to switch madly between various inconsistent states. Like wire cables drawing some sides as full-block sides and other sides as wire sides. My fix was to move enough of `RenderBlocks` into a new class `RenderBoxUtil` that maintains that state, and create a new instance of `RenderBoxUtil` during `GT_Renderer_Blocks.renderBlock()`.

I also found `BaseMeta{Pipe,Tile}Entity` were issuing way too many chunk updates in response to `receiveClientEvent` and `receiveMetaTileEntityData` without checking whether the event/data caused a state change that would necessitate the update.

**Comment by codewarrior0** [comment]
My commits related to that last bit merged cleanly... (PR #960)

...but now git is syncing another 30 megs or so of binaries. @Dragon2488, please, PLEASE don't keep binaries in the git repo. It's a pain in the ass for everyone. Just use GitHub Releases instead like a normal person.

**Comment by MauveCloud** [comment]
If you look at the history, I think it was actually laz2727 who committed the binaries to the repo.  Dragon2488 trimmed them down a bit.

Edit: also, Blood Asp hasn't been using GitHub releases; he's been using the forum thread and some OneDrive folders.

**Comment by MauveCloud** [comment]
> Models are missing because they're generated in game. As far as I'm aware.

That is probably a good way to do it, especially considering the json format used for them.  However, the related exception messages in the log suggest that they're being generated a bit late in the loading sequence.

**Comment by Dragon2488** [comment]
We can't generate them in tine because of the way how MetaTileEntity texturing works. Guess we can generate 6-side quads for every BlockIcon and use them later.

**Comment by Dragon2488** [comment]
*in time.
Simple block models can be done via jsons, too.

**Comment by Dragon2488** [comment]
But this dynamic texturing isn't solution.

**Comment by Dragon2488** [comment]
In fact, best solution would be to re-code metatileentity texture management

**Comment by ghost** [comment]
This is still happening in 10.41.

https://forum.industrial-craft.net/core/images/proxy/82/825f2cb3278f792dac380adb40edcef8ca211ec0.jpg

**Comment by Landbanana** [comment]
This is exactly what's happening to me! Whenever I have Optifine installed, every Gregtech block either goes one solid color or acts like an x-ray. As far as I've seen this has only happened with Gregtech. Has any progress been made with this?
