### ISSUE TITLE
ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by BlayzerQ** [Blood-Asp/GT5-Unofficial#935]
java.lang.ArrayIndexOutOfBoundsException: 0
	at gregtech.api.util.GT_Utility.getUndergroundOil(GT_Utility.java:1579)
	at gregtech.api.util.GT_Utility.getUndergroundOil(GT_Utility.java:1528)
	at gregtech.common.GT_Pollution.onWorldTick(GT_Pollution.java:95)
	at gregtech.common.GT_Proxy.onWorldTickEvent(GT_Proxy.java:1247)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_3_GT_Proxy_onWorldTickEvent_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DEMOOH** [comment]
@maixgame can you check this one? Related to this change https://github.com/Blood-Asp/GT5-Unofficial/commit/901a7d66c1766b3f21de4f74e696a30e5d178018

@BlayzerQ  Can you give full log? Full mod list is needed too.
Did you try to get oil in the vanilla overworld?

**Comment by BlayzerQ** [comment]
I updated mod to the latest version, then the players have done something and i get crash.
Full crash-log with mod list: http://paste.enginehub.org/pDWwsE
Full server-log:
[fml-server-1.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/821911/fml-server-1.txt)

**Comment by maixgame** [comment]
@BlayzerQ use this: https://yadi.sk/d/sg-AcFQO3FA7Gy
