### ISSUE TITLE
[1.10.2] GT cable adjacent to pipe causes pipe connections to go haywire, log spam

### ISSUE THREAD

**Issue by MauveCloud** [Blood-Asp/GT5-Unofficial#939]
When I placed a 4x tin cable 1 block above a large bronze pipe, the cable appeared to connect to the pipe, and the pipe started repeatedly cycling through various connection possibilities.  Additionally, the log started getting spammed with messages like this:
```
[15:46:31] [Server thread/ERROR] [gregtech]: Encountered Exception while ticking MetaTileEntity in Step 10. The Game should've crashed now, but I prevented that. Please report immidietly to GregTech Intergalactical!!!
[15:46:31] [Server thread/ERROR] [gregtech]: java.lang.NullPointerException
[15:46:31] [Server thread/ERROR] [gregtech]: 	at gregtech.api.GregTech_API.getCoverId(GregTech_API.java:427)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid.onPostTick(GT_MetaPipeEntity_Fluid.java:233)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_73660_a(BaseMetaPipeEntity.java:281)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.World.func_72939_s(World.java:1804)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at java.lang.Thread.run(Thread.java:745)
[15:46:31] [Server thread/ERROR] [gregtech]: Encountered Exception while ticking MetaTileEntity in Step 10. The Game should've crashed now, but I prevented that. Please report immidietly to GregTech Intergalactical!!!
[15:46:31] [Server thread/ERROR] [gregtech]: java.lang.NullPointerException
[15:46:31] [Server thread/ERROR] [gregtech]: 	at gregtech.api.GregTech_API.getCoverId(GregTech_API.java:427)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid.onPostTick(GT_MetaPipeEntity_Fluid.java:233)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_73660_a(BaseMetaPipeEntity.java:281)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.World.func_72939_s(World.java:1804)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[15:46:31] [Server thread/ERROR] [gregtech]: 	at java.lang.Thread.run(Thread.java:745)
[15:46:32] [Server thread/ERROR] [gregtech]: Encountered Exception while ticking MetaTileEntity in Step 10. The Game should've crashed now, but I prevented that. Please report immidietly to GregTech Intergalactical!!!
[15:46:32] [Server thread/ERROR] [gregtech]: java.lang.NullPointerException
[15:46:32] [Server thread/ERROR] [gregtech]: 	at gregtech.api.GregTech_API.getCoverId(GregTech_API.java:427)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid.onPostTick(GT_MetaPipeEntity_Fluid.java:233)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_73660_a(BaseMetaPipeEntity.java:281)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.World.func_72939_s(World.java:1804)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[15:46:32] [Server thread/ERROR] [gregtech]: 	at java.lang.Thread.run(Thread.java:745)
```
Placing the cable to the side of the pipe affected it similarly.

**Comment by MauveCloud** [comment]
Additional note: I discovered today that putting foil on a pipe to prevent connection with a cable does not stop it from cycling through connection possibilities or spamming the log with error messages.  I didn't look to see if the cable looked like it was connected to the pipe.

**Comment by Exidex** [comment]
Invalid because of rewrite.
