### ISSUE TITLE
item pipes not working in 1.10.2

### ISSUE THREAD

**Issue by JammerFTW** [Blood-Asp/GT5-Unofficial#944]
I have a bit of an issue, as in 1.10.2, i try to hopper items into a item pipe, but when i do, the pipe the hopper is connected to, fills, but the rest dont, and nothing appears in the inventory on the end.

**Comment by MauveCloud** [comment]
I'm curious how you determined that the first pipe fills - when I tried it in creative mode, one item was removed from the hopper, but item detectors on the pipes gave no indication of there being items in the pipes.  Also, the log showed several instances of errors like this:
```
[16:37:06] [Server thread/ERROR] [gregtech]: Encountered Exception while ticking MetaTileEntity in Step 10. The Game should've crashed now, but I prevented that. Please report immidietly to GregTech Intergalactical!!!
[16:37:06] [Server thread/ERROR] [gregtech]: java.lang.ArrayIndexOutOfBoundsException: 6
[16:37:06] [Server thread/ERROR] [gregtech]: 	at gregtech.api.util.GT_Utility.moveOneItemStack(GT_Utility.java:512)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at gregtech.api.util.GT_Utility.moveOneItemStack(GT_Utility.java:499)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Item.insertItemStackIntoTileEntity(GT_MetaPipeEntity_Item.java:250)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Item.sendItemStack(GT_MetaPipeEntity_Item.java:237)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Item.onPostTick(GT_MetaPipeEntity_Item.java:212)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_73660_a(BaseMetaPipeEntity.java:281)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.World.func_72939_s(World.java:1804)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[16:37:06] [Server thread/ERROR] [gregtech]: 	at java.lang.Thread.run(Thread.java:745)
```

The corresponding line in GT_Utility.java looks like this:
```
tGrabSlots = ((ISidedInventory) aTileEntity1).getSlotsForFace(EnumFacing.VALUES[aGrabFrom]);
```
I looked through the stack trace, and `aGrabFrom` is 6 here, which explains the ArrayIndexOutOfBoundsException.  However, in 5.09, the corresponding line looks like this with the same value for `aGrabFrom`:
```
tGrabSlots = ((ISidedInventory) aTileEntity1).getAccessibleSlotsFromSide(aGrabFrom);
```

I'm guessing that in 1.7.10, ISidedInventory.getAccessibleSlotsFromSide had special handling for a value of 6, but I don't know where to find out how to get similar handling in 1.10.2 (if it's even still possible).
