### ISSUE TITLE
GregTech NPE on WorldBorder's plugin chunk filling

### ISSUE THREAD

**Issue by Sirse** [Blood-Asp/GT5-Unofficial#990]
KCauldron, latest build

java.lang.NullPointerException
	at gregtech.common.blocks.GT_TileEntity_Ores.overrideOreBlockMaterial(GT_TileEntity_Ores.java:176)
	at gregtech.common.GT_Worldgen_Stone.executeWorldgen(GT_Worldgen_Stone.java:72)
	at gregtech.common.GT_Worldgenerator$WorldGenContainer.run(GT_Worldgenerator.java:105)
	at gregtech.common.GT_Worldgenerator.generate(GT_Worldgenerator.java:51)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:472)
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.chunkLoadPostProcess(CraftWorld.java:298)
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.loadChunk(CraftWorld.java:273)
	at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

**Comment by draknyte1** [comment]
Can't expect much else from a system not designed for Bukkit & Plugins,
Nor from a system that expects nothing outside standard MC behavior, exactly what GT doesn't use.

It's the plugins issue while mishandling GT data, not really Gregtechs.

**Comment by Dragon2488** [comment]
Your plugin removes tile entity of ore where gt excepts it. And yes, don't really except bukkit support.

**Comment by Blood-Asp** [comment]
Normaly no support for Bukkit&co. But adding a null check was 2min work, so i just did it.
